name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: pandoc/latex

    steps:
    - uses: actions/checkout@v3

    - name: Run test
      run: make test
